carts/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('', views.carts, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('greatkart.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('place_order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='product_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='search'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account


class Cart(models.Model):
    cart_id = models.CharField(max_length=255, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.cart_id


class CartItem(models.Model):
    user  = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __unicode__(self) -> str:
        return self.product
    

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    # get product
    product = Product.objects.get(id=product_id)

    # if the user is authenticated
    if current_user.is_authenticated:

        variation_list = []
        if request.method == "POST":
            # color = request.POST['color']
            # size = request.POST['size']
            # print("size", size, "color", color)
            for item in request.POST:
                key = item
                value = request.POST[key]
                print(key, value)
                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value)
                    variation_list.append(variation)
                except:
                    pass
    
        is_cart_item_exists = CartItem.objects.filter(
            product=product, user=current_user).exists()

        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            # existing variation in database
            # current variation
            # item id in databases should check
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if variation_list in ex_var_list:
                # increase the cart item quantity

                index = ex_var_list.index(variation_list)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    product=product, quantity=1, user=current_user)
                if len(variation_list) > 0:
                    item.variations.clear()
                    item.variations.add(*variation_list)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                user=current_user,
                quantity=1
            )
            if len(variation_list) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*variation_list)
            cart_item.save()
        return redirect('cart:cart')

    else:
        # else the user is not authenticated
        variation_list = []
        if request.method == "POST":
            # color = request.POST['color']
            # size = request.POST['size']
            # print("size", size, "color", color)
            for item in request.POST:
                key = item
                value = request.POST[key]
                print(key, value)
                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value)
                    variation_list.append(variation)
                except:
                    pass
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()
        is_cart_item_exists = CartItem.objects.filter(
            product=product, cart=cart).exists()

        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing variation in database
            # current variation
            # item id in databases should check
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if variation_list in ex_var_list:
                # increase the cart item quantity

                index = ex_var_list.index(variation_list)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    product=product, quantity=1, cart=cart)
                if len(variation_list) > 0:
                    item.variations.clear()
                    item.variations.add(*variation_list)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                cart=cart,
                quantity=1
            )
            if len(variation_list) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*variation_list)
            cart_item.save()
        return redirect('cart:cart')


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(
            product=product, cart=cart, id=cart_item_id)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart:cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product,user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(
            product=product, cart=cart, id=cart_item_id)
        cart_item.delete()
    except:
        pass
    return redirect('cart:cart')


def carts(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    context = {
        'total': total,
        'quantity': quantity,
        "cart_items": cart_items,
        "tax": tax,
        "grand_total": grand_total
    }
    return render(request, 'cart/cart.html', context)


@login_required(login_url="account:login")
def checkout(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    context = {
        'total': total,
        'quantity': quantity,
        "cart_items": cart_items,
        "tax": tax,
        "grand_total": grand_total
    }
    return render(request, 'cart/checkout.html', context)

templates/cart/cart.html
{% extends 'base.html' %} {% block content %} {% load static %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
    <h4 class="text-center">Your Shopping Cart is Empty !</h4>
    <div class="text-center">
      <a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping</a>
    </div>
    {% else %}
    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"></th>
              </tr>
            </thead>
            <tbody>
              
              {% for cart_item in cart_items %}
             
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside">
                      <img src="{{cart_item.product.images.url}}" class="img-sm" />
                    </div>
                    <figcaption class="info">
                      <a href="{{cart_item.product.get_product_url}}" class="title text-dark"
                        >{{cart_item.product.product_name}}</a
                      >
                      <p class="text-muted small">
                        {% if cart_item.variations.all %}
                        {% for item in cart_item.variations.all %}
                        {{item.variation_category| capfirst}} : {{item.variation_value| capfirst}}
                        <br>
                        {% endfor %}
                        {% endif %}
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <form action=""></form>
                        <a href="{% url 'cart:remove_cart' cart_item.product.id cart_item.id %}"
                          class="btn btn-light"
                          type="button"
                          id="button-plus"
                        >
                          <i class="fa fa-minus"></i>
                        </a>
                      </div>
                      <input type="text" class="form-control" value="{{cart_item.quantity}}" />
                      <div class="input-group-append">
                        <form action="{% url 'cart:add_cart' cart_item.product.id %}" method="POST">
                          {% csrf_token %}
                          {% for item in cart_item.variations.all %}
                          <input type="hidden" name="{{item.variation_category|lower}}" value="{{item.variation_value|capfirst}}">
                          {% endfor %}
                        <button href=""
                          class="btn btn-light"
                          type="submit"
                          id="button-minus"
                        >
                          <i class="fa fa-plus"></i>
                        </button>
                      </form>
                      </div>
                    </div>
                    <!-- input-group.// -->
                  </div>
                  <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">$ {{cart_item.sub_total}}</var>
                    <small class="text-muted"> $ {{cart_item.product.price}} each </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a href="{% url 'cart:remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to delete ths item ?')" class="btn btn-danger"> Remove</a>
                </td>
              </tr>
              {% endfor %}
             
            </tbody>
          </table>
          
        </div>

        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <aside class="col-lg-3">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">$ {{total}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              <dd class="text-right">$ {{tax}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Total:</dt>
              <dd class="text-right text-dark b"><strong>$ {{grand_total}}</strong></dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img src="{% static './images/misc/payments.png' %}" height="26" />
            </p>
            <a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block">
              Checkout
            </a>
            <a href="{% url 'store:store' %}" class="btn btn-light btn-block"
              >Continue Shopping</a
            >
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
    </div>
    {% endif %}
    <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/cart/checkout.html
{% extends 'base.html' %} {% block content %} {% load static %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
   
    <div class="row">
      <aside class="col-lg-6">
        <div class="card">
         <div class="card-body">
            <h4 class="card-title mb-4">Billing Address</h4>

            <form action="{% url 'place_order' %}" method="POST">
                {% csrf_token %}
                <div class="form-row mb-3">
                    <div class="col from-group">
                        <label for="">First Name</label>
                        <input type="text" class="form-control" name="first_name" placeholder="Enter Your Name">
                    </div>

                    <div class="col from-group">
                        <label for="">Last Name</label>
                        <input type="text" class="form-control" name="last_name" placeholder="Enter Your Last Name">
                    </div>
                </div>

                <div class="form-row  mb-3">
                    <div class="col from-group">
                        <label for="">Email Address</label>
                        <input type="email" class="form-control" name="email" placeholder="Enter Your email">
                    </div>

                    <div class="col from-group">
                        <label for="">phone Number</label>
                        <input type="text" class="form-control" name="phone" placeholder="Enter Your phone Number">
                    </div>
                </div>

                <div class="form-row  mb-3">
                    <div class="col from-group">
                        <label for="">Address Line 1</label>
                        <input type="text" class="form-control" name="address_line_1" placeholder="Enter Your address">
                    </div>

                    <div class="col from-group">
                        <label for="">Address Line 2</label>
                        <input type="text" class="form-control" name="address_line_2" placeholder="Enter Your address">
                    </div>
                </div>

                <div class="form-row  mb-3">
                    <div class="col from-group">
                        <label for="">City </label>
                        <input type="text" class="form-control" name="city" placeholder="Enter Your City">
                    </div>

                    <div class="col from-group">
                        <label for="">State</label>
                        <input type="text" class="form-control" name="state" placeholder="Enter Your state">
                    </div>

                    <div class="col from-group">
                        <label for="">Country</label>
                        <input type="text" class="form-control" name="country" placeholder="Enter Your country">
                    </div>
                </div>

                <div class="form-row">
                    <label for="">Order Note</label>
                   <textarea id="" cols="30" rows="4" name="order_note" class="form-control"></textarea>
                </div>           
         </div> 
        </div>

        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <aside class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                  <tr class="small text-uppercase">
                    <th scope="col">Product</th>
                    <th scope="col" width="120">Quantity</th>
                    <th scope="col" width="120">Price</th>
                    <th scope="col" class="text-right" width="200"></th>
                  </tr>
                </thead>
                <tbody>
                  
                  {% for cart_item in cart_items %}
                 
                  <tr>
                    <td>
                      <figure class="itemside align-items-center">
                        <div class="aside">
                          <img src="{{cart_item.product.images.url}}" class="img-sm" />
                        </div>
                        <figcaption class="info">
                          <p  class="title text-dark"
                            >{{cart_item.product.product_name}}</p
                          >
                          <p class="text-muted small">
                            {% if cart_item.variations.all %}
                            {% for item in cart_item.variations.all %}
                            {{item.variation_category| capfirst}} : {{item.variation_value| capfirst}}
                            <br>
                            {% endfor %}
                            {% endif %}
                          </p>
                        </figcaption>
                      </figure>
                    </td>
                    <td>
                      <!-- col.// -->
                      <div class="col">
                        <div class="input-group input-spinner">
                          <div class="input-group-prepend">
                            <label for="">{{cart_item.quantity}}</label>
                          </div>
                        </div>
                        <!-- input-group.// -->
                      </div>
                      <!-- col.// -->
                    </td>
                    <td>
                      <div class="price-wrap">
                        <var class="price">$ {{cart_item.sub_total}}</var>
                        <small class="text-muted"> $ {{cart_item.product.price}} each </small>
                      </div>
                      <!-- price-wrap .// -->
                    </td>
                    
                  </tr>
                  {% endfor %}
                 
                </tbody>
                
              </table>
              <hr>
            <button type="submit" class="btn btn-primary btn-block">
              place Order
            </button>
            <a href="{% url 'store:store' %}" class="btn btn-light btn-block"
              >Continue Shopping</a
            >
          </div>
          <!-- card-body.// -->
        </form>
        </div>
        <!-- card.// -->
      </aside>
    
      <!-- col.// -->
    </div>
   
    <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}