carts/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('', views.carts, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('greatkart.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('place_order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='product_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='search'),
]

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse


class Product(models.Model):
    product_name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products/')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.product_name

    def get_product_url(self):
        return reverse('store:product_detail', args=[self.category.slug, self.slug])


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size',is_active = True)


VARIATION_CATEGORY_CHOICES = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=255, choices=VARIATION_CATEGORY_CHOICES)
    variation_value = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    
    objects = VariationManager()
    
    def __unicode__(self) -> str:
        return self.product
    
    

store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from category.models import Category
from . models import Product
from carts.models import CartItem
from carts.views import _cart_id
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.db.models import Q


def store(request, category_slug=None):
    categories = None
    products = None
    # try:
    #     categories = Category.objects.get(slug=category_slug)
    # except Category.DoesNotExist:
    #     return HttpResponse(f'Category with {category_slug} does not exist!!!')
    if category_slug != None:
        # Using Try ana except
        categories = get_object_or_404(
            Category, slug=category_slug)
        products = Product.objects.filter(
            category=categories, is_available=True)
        paginator = Paginator(products, 4)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

    context = {
        "products": paged_products,
        "product_count": product_count
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(
            category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(
            request), product=single_product).exists()

    except Exception as e:
        raise e
    context = {
        "single_product": single_product,
        "in_cart": in_cart
    }
    return render(request, 'store/product_detail.html', context)


def product_search(request):
    if 'query_search' in request.GET:
        query_search = request.GET['query_search']
        if query_search:
            products = Product.objects.order_by('-created_at').filter(
                Q(description__icontains=query_search) |
                Q(product_name__icontains=query_search))
            product_count = products.count()
    context = {
        'products': products,
        "product_count": product_count
    }
    return render(request, 'store/store.html', context)

templates/store/home.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
  <div class="container">
    <div class="intro-banner-wrap">
      <img
        src="{% static 'images/banners/cover.jpg' %}"
        class="img-fluid rounded"
      />
    </div>
  </div>
  <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
  <div class="container">
    <header class="section-heading">
      <a href="{% url 'store:store' %}" class="btn btn-outline-primary float-right"
        >See all</a
      >
      <h3 class="section-title">Popular products</h3>
    </header>
    <!-- Container Pages -->

    <div class="row">
      {% for product in products %}
      <div class="col-md-3">
        <div class="card card-product-grid">
          <a href="{{product.get_product_url}}" class="img-wrap">
            <img src="{{product.images.url}}" />
          </a>
          <figcaption class="info-wrap">
            <a href="{{product.get_product_url}}" class="title"
              >{{product.product_name}}</a
            >
            <div class="price mt-1">${{product.price}}</div>
          </figcaption>
        </div>
      </div>
      {% endfor %}
    </div>

    {% endblock %}
  </div>
</section>

templates/store/product_detail.html
{% extends 'base.html' %} {% block content %} {% load static %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap">
              <a href="#"><img src="{{single_product.images.url}}" /></a>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'cart:add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{single_product.product_name}}</h2>

              <div class="mb-3">
                <var class="price h4">${{single_product.price}}</var>
              </div>

              <p>{{single_product.description}}</p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name="color" id="" class="form-control"  required>
                    <option value="" disabled selected>Choose Color</option>
                    
                    {% for i in single_product.variation_set.colors %}
                    <option value="{{i.variation_value| lower}}">{{i.variation_value| capfirst}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="size" id="" class="form-control">
                    <option value="" disabled selected>Choose Size</option>
                    {% for i in single_product.variation_set.sizes %}
                    <option value="{{i.variation_value| lower}}">{{i.variation_value| capfirst}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if single_product.stock <= 0 %}
              <h3 class="text-danger">Out of Stock</h3>
              {% else %} 
    
              <button
               type="submit"
                class="btn btn-primary"
              >
                <span class="text">Add to cart</span>
                <i class="fas fa-shopping-cart"></i>
              </button>
              {% endif %} 
              
            </article>
          </form>
          <!-- product-info-aside .// -->
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        <header class="section-heading">
          <h3>Customer Reviews</h3>
        </header>

        <article class="box mb-3">
          <div class="icontext w-100">
            <img
              src="{% static './images/avatars/avatar1.jpg' %}"
              class="img-xs icon rounded-circle"
            />
            <div class="text">
              <span class="date text-muted float-md-right">24.04.2020 </span>
              <h6 class="mb-1">Mike John</h6>
            </div>
          </div>
          <!-- icontext.// -->
          <div class="mt-3">
            <p>
              Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing
              elit, sed do eiusmod tempor incididunt ut labore et dolore magna
              aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
              laboris nisi ut aliquip
            </p>
          </div>
        </article>
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/store.html
{% extends 'base.html' %}

{% block content %}


<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
  {% if 'search' in request.path %}
  <div class="container">

    <h2 class="title-page ">Search Result</h2>
  </div>
  {% else %}
  <div class="container">
    <h2 class="title-page">Our Store</h2>
    
  </div> <!-- container //  --> 
  {% endif %}
  </section>
  <!-- ========================= SECTION INTRO END// ========================= -->
  
  <!-- ========================= SECTION CONTENT ========================= -->
  <section class="section-content padding-y">
  <div class="container">
  
  <div class="row">
    <aside class="col-md-3">
      
  <div class="card">
    <article class="filter-group">
      <header class="card-header">
        <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
          <i class="icon-control fa fa-chevron-down"></i>
          <h6 class="title">Categories</h6>
        </a>
      </header>
      <div class="filter-content collapse show" id="collapse_1" style="">
        <div class="card-body">
          
          <ul class="list-menu">
            {% for cat in categories %}
          <li><a href="{% url 'store:product_by_category' cat.slug %}">{{cat.category_name}}  </a></li>

          {% endfor %}
          
          </ul>
  
        </div> <!-- card-body.// -->
      </div>
    </article> <!-- filter-group  .// -->
    <article class="filter-group">
      <header class="card-header">
        <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
          <i class="icon-control fa fa-chevron-down"></i>
          <h6 class="title">Sizes </h6>
        </a>
      </header>
      <div class="filter-content collapse show" id="collapse_4" style="">
        <div class="card-body">
          <label class="checkbox-btn">
            <input type="checkbox">
            <span class="btn btn-light"> XS </span>
          </label>
  
          <label class="checkbox-btn">
            <input type="checkbox">
            <span class="btn btn-light"> SM </span>
          </label>
  
          <label class="checkbox-btn">
            <input type="checkbox">
            <span class="btn btn-light"> LG </span>
          </label>
  
          <label class="checkbox-btn">
            <input type="checkbox">
            <span class="btn btn-light"> XXL </span>
          </label>
      </div><!-- card-body.// -->
      </div>
    </article> <!-- filter-group .// -->
    
    <article class="filter-group">
      <header class="card-header">
        <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
          <i class="icon-control fa fa-chevron-down"></i>
          <h6 class="title">Price range </h6>
        </a>
      </header>
      <div class="filter-content collapse show" id="collapse_3" style="">
        <div class="card-body">
          
          <div class="form-row">
          <div class="form-group col-md-6">
            <label>Min</label>
            <!-- <input class="form-control" placeholder="$0" type="number"> -->
              <select class="mr-2 form-control">
              <option value="0">$0</option>
              <option value="50">$50</option>
              <option value="100">$100</option>
              <option value="150">$150</option>
              <option value="200">$200</option>
              <option value="500">$500</option>
              <option value="1000">$1000</option>
            </select>
          </div>
          <div class="form-group text-right col-md-6">
            <label>Max</label>
              <select class="mr-2 form-control">
              <option value="50">$50</option>
              <option value="100">$100</option>
              <option value="150">$150</option>
              <option value="200">$200</option>
              <option value="500">$500</option>
              <option value="1000">$1000</option>
              <option value="2000">$2000+</option>
            </select>
          </div>
          </div> <!-- form-row.// -->
          <button class="btn btn-block btn-primary">Apply</button>
        </div><!-- card-body.// -->
      </div>
    </article> <!-- filter-group .// -->
    
  </div> <!-- card.// -->
  
    </aside> <!-- col.// -->
    <main class="col-md-9">
  
  <header class="border-bottom mb-4 pb-3">
      <div class="form-inline">
        <span class="mr-md-auto">{{product_count}} Items found </span>
        
      </div>
  </header><!-- sect-heading -->
  
  <div class="row">
    {% if products %}

    {% for product in products %}
    <div class="col-md-4">
      <figure class="card card-product-grid">
        <div class="img-wrap"> 
          
          <img src="{{product.images.url}}">
          
        </div> <!-- img-wrap.// -->
        <figcaption class="info-wrap">
          <div class="fix-height">
            <a href="{{product.get_product_url}}" class="title">{{product.product_name}}</a>
            <div class="price-wrap mt-2">
              <span class="price">$ {{product.price}}</span>
              
            </div> <!-- price-wrap.// -->
          </div>
          <a href="{{product.get_product_url}}" class="btn btn-block btn-primary">View Detail </a>
        </figcaption>
      </figure>
    </div> <!-- col.// -->
  {% endfor %}
  {% else %}
  <h2>Not Result Found, please try again.</h2>
  {% endif %}
    
    
  </div> <!-- row end.// -->
  
  
  <nav class="mt-4" aria-label="Page navigation sample">
    {% if products.has_other_pages %}
    <ul class="pagination">
      {% if products.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>

      {% endif %}
      {% for i in products.paginator.page_range %}
        {% if products.number == i %}
      <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>

      {% else %}
      <li class="page-item "><a class="page-link" href="?page={{i}}">{{i}}</a></li>
      {% endif %}

      {% endfor %}

      {% if products.has_next %}
      <li class="page-item "><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
      {% endif %}
    </ul>
    {% endif %}
  </nav>
  
    </main> <!-- col.// -->
  
  </div>
  
  </div> <!-- container .//  -->
  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}